DROP SCHEMA IF EXISTS POKEMON_LEAGUE CASCADE;

CREATE SCHEMA POKEMON_LEAGUE;

CREATE TABLE POKEMON_LEAGUE.LEAGUE (
    LEAGUE_ID       INTEGER         PRIMARY KEY,
    LEAGUE_NAME     VARCHAR(50)     NOT NULL,
    REGION          VARCHAR(50)     NOT NULL,
    BATTLE_COUNT    INTEGER         NOT NULL CHECK (BATTLE_COUNT > 0)
);

CREATE TABLE POKEMON_LEAGUE.BATTLE (
    LEAGUE_ID       INTEGER         REFERENCES POKEMON_LEAGUE.LEAGUE (LEAGUE_ID),
    BATTLE_ID       INTEGER         PRIMARY KEY,
    ARENA           VARCHAR(50)     NOT NULL,
    ROUND_COUNT     INTEGER         NOT NULL CHECK (ROUND_COUNT > 0)
);

CREATE TABLE POKEMON_LEAGUE.PLAYER (
    PLAYER_ID        INTEGER         PRIMARY KEY,
    PLAYER_NAME             VARCHAR(50)     NOT NULL,
    DATE_OF_BIRTH    DATE,
    REGION           VARCHAR(50)     NOT NULL,
    STATUS           VARCHAR(50)     NOT NULL DEFAULT 'Новичок'
);

CREATE TABLE POKEMON_LEAGUE.ROUND (
    ROUND_ID        INTEGER         PRIMARY KEY,
    BATTLE_ID       INTEGER         REFERENCES POKEMON_LEAGUE.BATTLE (BATTLE_ID),
    WINNER_ID       INTEGER         REFERENCES POKEMON_LEAGUE.PLAYER (PLAYER_ID),
    ROUND_DATE      DATE,
    PLAYER_COUNT    INTEGER         NOT NULL CHECK (PLAYER_COUNT > 0)
                                  DEFAULT 2
);

CREATE TABLE POKEMON_LEAGUE.POKEMON (
    POKEMON_ID       INTEGER         PRIMARY KEY,
    PLAYER_ID        INTEGER         REFERENCES POKEMON_LEAGUE.PLAYER (PLAYER_ID),
    POKEMON_NAME     VARCHAR(50)     NOT NULL,
    GENDER           CHAR            NOT NULL DEFAULT 'Н',
    AGE              INTEGER         NOT NULL,
    HIGH             NUMERIC(10, 2)  NOT NULL,
    WEIGHT           NUMERIC(10, 2)  NOT NULL
);

CREATE TABLE POKEMON_LEAGUE.TYPE (
    TYPE_ID            INTEGER         PRIMARY KEY,
    TYPE_NAME          VARCHAR(50)     NOT NULL,
    SPECIES_COUNT      INTEGER         NOT NULL CHECK(TYPE.SPECIES_COUNT >0) DEFAULT 1
);

CREATE TABLE POKEMON_LEAGUE.ROUND_X_PLAYER(
    ROUND_ID        INTEGER         REFERENCES POKEMON_LEAGUE.ROUND (ROUND_ID),
    PLAYER_ID       INTEGER         REFERENCES POKEMON_LEAGUE.PLAYER (PLAYER_ID)
);

CREATE TABLE POKEMON_LEAGUE.ROUND_X_POKEMON(
    ROUND_ID        INTEGER         REFERENCES POKEMON_LEAGUE.ROUND (ROUND_ID),
    POKEMON_ID      INTEGER         REFERENCES POKEMON_LEAGUE.POKEMON (POKEMON_ID)
);

CREATE TABLE POKEMON_LEAGUE.POKEMON_X_TYPE (
    POKEMON_ID      INTEGER         REFERENCES POKEMON_LEAGUE.POKEMON (POKEMON_ID),
    TYPE_ID        INTEGER         REFERENCES POKEMON_LEAGUE.TYPE (TYPE_ID)
);
