/* участниики боя */

CREATE OR REPLACE VIEW BATTLE_X_PLAYER_VIEW AS
    SELECT DISTINCT BATTLE.BATTLE_ID AS BATTLE_INDEX, PLAYER.PLAYER_NAME
    FROM POKEMON_LEAGUE.BATTLE
    INNER JOIN POKEMON_LEAGUE.ROUND ON BATTLE.BATTLE_ID = ROUND.BATTLE_ID
    INNER JOIN POKEMON_LEAGUE.ROUND_X_PLAYER ON ROUND.ROUND_ID = ROUND_X_PLAYER.ROUND_ID
    INNER JOIN POKEMON_LEAGUE.PLAYER ON ROUND_X_PLAYER.PLAYER_ID = PLAYER.PLAYER_ID
    ORDER BY BATTLE.BATTLE_ID, PLAYER.PLAYER_NAME;

SELECT *
FROM BATTLE_X_PLAYER_VIEW;

/* количество покемонов каждого типа у участников */

CREATE OR REPLACE VIEW PLAYER_X_POKEMON_X_TYPE_VIEW AS
    SELECT PLAYER_NAME, TYPE_NAME, SUM(CASE WHEN (T.POKEMON_ID IS NULL) THEN 0 ELSE 1 END )
    FROM POKEMON_LEAGUE.PLAYER
    FULL JOIN POKEMON_LEAGUE.TYPE ON TRUE
    LEFT JOIN (SELECT POKEMON.POKEMON_ID, POKEMON_X_TYPE.TYPE_ID, POKEMON.PLAYER_ID
            FROM POKEMON_LEAGUE.POKEMON
            LEFT JOIN POKEMON_LEAGUE.POKEMON_X_TYPE ON POKEMON.POKEMON_ID = POKEMON_X_TYPE.POKEMON_ID) AS T
        ON T.TYPE_ID = TYPE.TYPE_ID AND PLAYER.PLAYER_ID = T.PLAYER_ID
    GROUP BY (PLAYER.PLAYER_ID, TYPE.TYPE_ID)
    ORDER BY PLAYER_NAME, TYPE_NAME;

SELECT *
FROM PLAYER_X_POKEMON_X_TYPE_VIEW;
