CREATE OR REPLACE VIEW LEAGUE_VIEW AS
    SELECT LEAGUE_NAME, REGION, BATTLE_COUNT
    FROM POKEMON_LEAGUE.LEAGUE;

SELECT *
FROM LEAGUE_VIEW;

CREATE OR REPLACE VIEW BATTLE_VIEW AS
    SELECT ARENA, ROUND_COUNT
    FROM POKEMON_LEAGUE.BATTLE;

SELECT *
FROM BATTLE_VIEW;

CREATE OR REPLACE VIEW ROUND_VIEW AS
    SELECT ROUND_DATE, PLAYER_COUNT, PLAYER_NAME AS WINNER
    FROM POKEMON_LEAGUE.ROUND
    INNER JOIN POKEMON_LEAGUE.PLAYER ON ROUND.WINNER_ID = PLAYER.PLAYER_ID;

SELECT *
FROM ROUND_VIEW;

CREATE OR REPLACE VIEW PLAYER_VIEW AS
    SELECT PLAYER_NAME, EXTRACT(YEAR FROM AGE(DATE_OF_BIRTH)) AS AGE, REGION, STATUS
    FROM POKEMON_LEAGUE.PLAYER;

SELECT *
FROM PLAYER_VIEW;

CREATE OR REPLACE VIEW POKEMON_VIEW AS
    SELECT POKEMON_NAME, PLAYER_NAME AS OWNER_NAME, GENDER, regexp_replace(AGE::text, '(.)', '*', 'g') AS AGE,
           regexp_replace(HIGH::text, '(.)', '*', 'g') AS HIGH,
           regexp_replace(WEIGHT::text, '(.)', '*', 'g') AS WEIGHT
    FROM POKEMON_LEAGUE.POKEMON
    INNER JOIN POKEMON_LEAGUE.PLAYER ON POKEMON.PLAYER_ID = PLAYER.PLAYER_ID;

SELECT *
FROM POKEMON_VIEW;

CREATE OR REPLACE VIEW TYPE_VIEW AS
    SELECT TYPE_NAME, SPECIES_COUNT
    FROM POKEMON_LEAGUE.TYPE;

SELECT *
FROM TYPE_VIEW;
